import AliveForTime from "./aliveForTime";
import AnimateSize from "./animateSize";
import Body from "./body";
import { Bounce } from "./bounce";
import Box from "./box";
import { Camera } from "./camera";
import { CanvasRenderer } from "./canvasRenderer";
import { Circle } from "./circle";
import { Collider } from "./collider";
import { ColliderRenderer } from "./colliderRenderer";
import { CollisionTexture } from "./collisionTexture";
import ContactTracker from "./contactTracker";
import Damage from "./damage";
import Explodes from "./explodes";
import FlipWithMouse from "./flipWithMouse";
import { FollowTransform } from "./followTransform";
import GroundTiler from "./groundTiler";
import Health from "./health";
import Hull from "./hull";
import Line from "./line";
import LookAtMouse from "./lookAtMouse";
import ParticleEmitter from "./particleEmitter";
import Player from "./player";
import Powerup from "./powerup";
import Powerupable from "./powerupable";
import RemoveWhenFar from "./removeWhenFar";
import { Replaceable } from "./replaceable";
import Score from "./score";
import Spawn from "./spawn";
import { StayOnMouse } from "./stayOnMouse";
import { Tag } from "./tag";
import { Text } from "./text";
import { Transform } from "./transform";
import VelocityClamp from "./velocityClamp";
import Weapon from "./weapon";

export type Component = AliveForTime | AnimateSize | Body | Bounce | Box | Camera | CanvasRenderer | Circle | Collider | ColliderRenderer | CollisionTexture | ContactTracker | Damage | Explodes | FlipWithMouse | FollowTransform | GroundTiler | Health | Hull | Line | LookAtMouse | ParticleEmitter | Player | Powerup | Powerupable | RemoveWhenFar | Replaceable | Score | Spawn | StayOnMouse | Tag | Text | Transform | VelocityClamp | Weapon;
